# Use the official Golang image as the builder
FROM golang:1.20 AS builder

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY main.go .

RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o hello

# Start a new stage from scratch using a smaller base image
FROM scratch

WORKDIR /app

COPY --from=builder /app/hello .

ENTRYPOINT ["/app/hello"]